apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: cu72to584-java-springboot
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/jsmid/rhtap-qe:01d0218c2d56159f89739d8a581cc3022a8adac7@sha256:9a165115aac0271a93c0544a514056f69f792cae0fe2d2fc4e5e134c1e53c214
          name: container-image
